# Generated by Django 3.2.7 on 2021-11-20 12:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('favorite_books_app', '0002_book_uploaded_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='likes',
            field=models.ManyToManyField(related_name='likesed_books', to='favorite_books_app.User'),
        ),
    ]
